<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\MstFasemonitor;

class MstFasemonitorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // $fasemonitors = [
        //     [
        //         'id_monitor' => 1,
        //         'grub_fasemonitor' => 'Persiapan Lahan',
        //         'fase_monitoring' => 'Pembersihan Lahan',
        //         'parameter' => 'Kebersihan',
        //         'titik_kritis' => 'Sisa tanaman dan gulma',
        //         'monitoring_poin' => 'Memastikan lahan bersih dari sisa tanaman sebelumnya',
        //         'bobot' => '20',
        //         'keterangan' => 'Fase awal sebelum penanaman',
        //         'field1' => '',
        //         'field2' => '',
        //     ],
        //     [
        //         'id_monitor' => 2,
        //         'grub_fasemonitor' => 'Persiapan Lahan',
        //         'fase_monitoring' => 'Pengolahan Tanah',
        //         'parameter' => 'Struktur Tanah',
        //         'titik_kritis' => 'Kegemburan tanah',
        //         'monitoring_poin' => 'Tanah harus gembur dan siap tanam',
        //         'bobot' => '20',
        //         'keterangan' => 'Pengolahan dengan bajak atau cangkul',
        //         'field1' => '',
        //         'field2' => '',
        //     ],
        //     [
        //         'id_monitor' => 3,
        //         'grub_fasemonitor' => 'Penanaman',
        //         'fase_monitoring' => 'Pemilihan Benih',
        //         'parameter' => 'Kualitas Benih',
        //         'titik_kritis' => 'Daya kecambah minimal 80%',
        //         'monitoring_poin' => 'Benih harus bersertifikat dan berkualitas',
        //         'bobot' => '15',
        //         'keterangan' => 'Gunakan benih unggul',
        //         'field1' => '',
        //         'field2' => '',
        //     ],
        //     [
        //         'id_monitor' => 4,
        //         'grub_fasemonitor' => 'Penanaman',
        //         'fase_monitoring' => 'Jarak Tanam',
        //         'parameter' => 'Spacing',
        //         'titik_kritis' => 'Jarak tanam sesuai standar',
        //         'monitoring_poin' => 'Jarak tanam harus optimal untuk pertumbuhan',
        //         'bobot' => '10',
        //         'keterangan' => 'Sesuai dengan jenis tanaman',
        //         'field1' => '',
        //         'field2' => '',
        //     ],
        //     [
        //         'id_monitor' => 5,
        //         'grub_fasemonitor' => 'Pemeliharaan',
        //         'fase_monitoring' => 'Penyiraman',
        //         'parameter' => 'Kelembaban',
        //         'titik_kritis' => 'Kelembaban tanah',
        //         'monitoring_poin' => 'Tanah tidak boleh terlalu kering atau tergenang',
        //         'bobot' => '15',
        //         'keterangan' => 'Sesuaikan dengan kebutuhan air tanaman',
        //         'field1' => '',
        //         'field2' => '',
        //     ],
        //     [
        //         'id_monitor' => 6,
        //         'grub_fasemonitor' => 'Pemeliharaan',
        //         'fase_monitoring' => 'Pemupukan',
        //         'parameter' => 'Nutrisi',
        //         'titik_kritis' => 'Dosis pupuk',
        //         'monitoring_poin' => 'Pemupukan sesuai umur dan kebutuhan tanaman',
        //         'bobot' => '15',
        //         'keterangan' => 'Gunakan pupuk organik dan anorganik',
        //         'field1' => '',
        //         'field2' => '',
        //     ],
        //     [
        //         'id_monitor' => 7,
        //         'grub_fasemonitor' => 'Pengendalian',
        //         'fase_monitoring' => 'Hama dan Penyakit',
        //         'parameter' => 'Serangan OPT',
        //         'titik_kritis' => 'Intensitas serangan',
        //         'monitoring_poin' => 'Monitoring rutin untuk deteksi dini',
        //         'bobot' => '20',
        //         'keterangan' => 'Pengendalian terpadu',
        //         'field1' => '',
        //         'field2' => '',
        //     ],
        //     [
        //         'id_monitor' => 8,
        //         'grub_fasemonitor' => 'Panen',
        //         'fase_monitoring' => 'Waktu Panen',
        //         'parameter' => 'Umur Tanaman',
        //         'titik_kritis' => 'Kematangan optimal',
        //         'monitoring_poin' => 'Panen pada waktu yang tepat',
        //         'bobot' => '10',
        //         'keterangan' => 'Sesuai dengan karakteristik komoditas',
        //         'field1' => '',
        //         'field2' => '',
        //     ],
        // ];

        // ini yang sesuai database

        $fasemonitors = [
            [
                'id_monitor' => 1,
                'grub_fasemonitor' => 'Biaya',
                'fase_monitoring' => 'Realisasi Biaya Mingguan',
                'parameter' => 'I. BPL',
                'titik_kritis' => '7.000.000',
                'monitoring_poin' => 'H-30 S/d Selesai Panen',
                'bobot' => '16.0%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 2,
                'grub_fasemonitor' => 'Biaya',
                'fase_monitoring' => 'Realisasi Biaya Mingguan',
                'parameter' => 'II. PERSIAPAN TANAM',
                'titik_kritis' => '5.740.000',
                'monitoring_poin' => 'H-30 S/d Selesai Panen',
                'bobot' => '13.1%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 3,
                'grub_fasemonitor' => 'Biaya',
                'fase_monitoring' => 'Realisasi Biaya Mingguan',
                'parameter' => 'III. TANAM DAN PEMELIHARAAN',
                'titik_kritis' => '8.362.000',
                'monitoring_poin' => 'H-30 S/d Selesai Panen',
                'bobot' => '19.1%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 4,
                'grub_fasemonitor' => 'Biaya',
                'fase_monitoring' => 'Realisasi Biaya Mingguan',
                'parameter' => 'IV. PENGAIRAN',
                'titik_kritis' => '6.750.000',
                'monitoring_poin' => 'H-30 S/d Selesai Panen',
                'bobot' => '15.4%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 5,
                'grub_fasemonitor' => 'Biaya',
                'fase_monitoring' => 'Realisasi Biaya Mingguan',
                'parameter' => 'V. PANEN',
                'titik_kritis' => '2.203.600',
                'monitoring_poin' => 'H-30 S/d Selesai Panen',
                'bobot' => '5.0%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 6,
                'grub_fasemonitor' => 'Biaya',
                'fase_monitoring' => 'Realisasi Biaya Mingguan',
                'parameter' => 'VI. UMUM',
                'titik_kritis' => '-',
                'monitoring_poin' => 'H-30 S/d Selesai Panen',
                'bobot' => '0.0%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 7,
                'grub_fasemonitor' => 'Biaya',
                'fase_monitoring' => 'Realisasi Biaya Mingguan',
                'parameter' => 'VII. TRANPORTASI',
                'titik_kritis' => '-',
                'monitoring_poin' => 'H-30 S/d Selesai Panen',
                'bobot' => '0.0%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 8,
                'grub_fasemonitor' => 'Biaya',
                'fase_monitoring' => 'Realisasi Biaya Mingguan',
                'parameter' => 'VIII. SAPROTAN',
                'titik_kritis' => '13.829.515',
                'monitoring_poin' => 'H-30 S/d Selesai Panen',
                'bobot' => '31.5%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 9,
                'grub_fasemonitor' => 'Biaya',
                'fase_monitoring' => 'Realisasi Biaya Mingguan',
                'parameter' => 'JUMLAH',
                'titik_kritis' => '43.885.115',
                'monitoring_poin' => 'H-30 S/d Selesai Panen',
                'bobot' => '100.0%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 10,
                'grub_fasemonitor' => 'Teknis',
                'fase_monitoring' => 'Persiapan Tanam',
                'parameter' => 'Olah tanah',
                'titik_kritis' => 'Kedalaman olah tanah $\\le$ 20cm',
                'monitoring_poin' => 'H-2 S/d H+3 Sesudah Tanam',
                'bobot' => '20%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 11,
                'grub_fasemonitor' => 'Teknis',
                'fase_monitoring' => 'Persiapan Tanam',
                'parameter' => 'Media Tanam',
                'titik_kritis' => 'Rata dan gembur',
                'monitoring_poin' => 'H-2 S/d H+3 Sesudah Tanam',
                'bobot' => '40%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 12,
                'grub_fasemonitor' => 'Teknis',
                'fase_monitoring' => 'Persiapan Tanam',
                'parameter' => 'Drainase',
                'titik_kritis' => 'Pembuangan lancar',
                'monitoring_poin' => 'H-2 S/d H+3 Sesudah Tanam',
                'bobot' => '10%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 13,
                'grub_fasemonitor' => 'Teknis',
                'fase_monitoring' => 'Persiapan Tanam',
                'parameter' => 'Pengairan',
                'titik_kritis' => '1. Irigasi teknis\r\n2. Irigasi Non teknis/tadahan hu...',
                'monitoring_poin' => 'H-2 S/d H+3 Sesudah Tanam',
                'bobot' => '10%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 14,
                'grub_fasemonitor' => 'Teknis',
                'fase_monitoring' => 'Persiapan Tanam',
                'parameter' => 'Gulma',
                'titik_kritis' => 'Permukaan bersih dari gulma/tanaman sebelumnya',
                'monitoring_poin' => 'H-2 S/d H+3 Sesudah Tanam',
                'bobot' => '20%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 15,
                'grub_fasemonitor' => 'Teknis',
                'fase_monitoring' => 'Vegetatif awal',
                'parameter' => 'Populasi tanaman',
                'titik_kritis' => '200 tanaman/ha',
                'monitoring_poin' => 'H+10 S/d H+15',
                'bobot' => '30%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 16,
                'grub_fasemonitor' => 'Teknis',
                'fase_monitoring' => 'Vegetatif awal',
                'parameter' => 'Pemupukan',
                'titik_kritis' => 'Tepat cara, tepat dosis',
                'monitoring_poin' => 'H+10 S/d H+15',
                'bobot' => '10%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 17,
                'grub_fasemonitor' => 'Teknis',
                'fase_monitoring' => 'Vegetatif awal',
                'parameter' => 'Tutupi Blok',
                'titik_kritis' => 'Permukaan bedeng tertutup tanah dan rata',
                'monitoring_poin' => 'H+10 S/d H+15',
                'bobot' => '20%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 18,
                'grub_fasemonitor' => 'Teknis',
                'fase_monitoring' => 'Vegetatif awal',
                'parameter' => 'Bemusca tembaci',
                'titik_kritis' => 'Serangan dibawah ambang kendali',
                'monitoring_poin' => 'H+10 S/d H+15',
                'bobot' => '9%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 19,
                'grub_fasemonitor' => 'Teknis',
                'fase_monitoring' => 'Vegetatif awal',
                'parameter' => 'Thrips',
                'titik_kritis' => 'Serangan dibawah ambang kendali',
                'monitoring_poin' => 'H+10 S/d H+15',
                'bobot' => '5%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 20,
                'grub_fasemonitor' => 'Teknis',
                'fase_monitoring' => 'Vegetatif awal',
                'parameter' => 'Ulat',
                'titik_kritis' => 'Serangan dibawah ambang kendali',
                'monitoring_poin' => 'H+10 S/d H+15',
                'bobot' => '2%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 21,
                'grub_fasemonitor' => 'Teknis',
                'fase_monitoring' => 'Vegetatif awal',
                'parameter' => 'Phylum',
                'titik_kritis' => 'Serangan dibawah ambang kendali',
                'monitoring_poin' => 'H+10 S/d H+15',
                'bobot' => '2%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 22,
                'grub_fasemonitor' => 'Teknis',
                'fase_monitoring' => 'Vegetatif awal',
                'parameter' => 'Kecukupan air',
                'titik_kritis' => 'Tanaman segar, tidak layu',
                'monitoring_poin' => 'H+10 S/d H+15',
                'bobot' => '15%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 23,
                'grub_fasemonitor' => 'Teknis',
                'fase_monitoring' => 'Generatif awal',
                'parameter' => 'Kecukupan air',
                'titik_kritis' => 'Permukaan bedeng kering namun tanaman tidak layu',
                'monitoring_poin' => 'H+25 S/d H+40',
                'bobot' => '15%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 24,
                'grub_fasemonitor' => 'Teknis',
                'fase_monitoring' => 'Generatif awal',
                'parameter' => 'Gulma',
                'titik_kritis' => 'Keberadaan gulma masih belum mengganggu tanaman',
                'monitoring_poin' => 'H+35 S/d H+40',
                'bobot' => '15%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 25,
                'grub_fasemonitor' => 'Teknis',
                'fase_monitoring' => 'Generatif awal',
                'parameter' => 'Virus',
                'titik_kritis' => 'Serangan dibawah ambang kendali',
                'monitoring_poin' => 'H+35 S/d H+40',
                'bobot' => '30%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 26,
                'grub_fasemonitor' => 'Teknis',
                'fase_monitoring' => 'Generatif awal',
                'parameter' => 'Bemisia tabaci',
                'titik_kritis' => 'Serangan dibawah ambang kendali',
                'monitoring_poin' => 'H+35 S/d H+40',
                'bobot' => '30%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 27,
                'grub_fasemonitor' => 'Teknis',
                'fase_monitoring' => 'Generatif awal',
                'parameter' => 'Ulat',
                'titik_kritis' => 'Serangan dibawah ambang kendali',
                'monitoring_poin' => 'H+35 S/d H+40',
                'bobot' => '5%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 28,
                'grub_fasemonitor' => 'Teknis',
                'fase_monitoring' => 'Generatif awal',
                'parameter' => 'Empoasca',
                'titik_kritis' => 'Serangan dibawah ambang kendali',
                'monitoring_poin' => 'H+35 S/d H+40',
                'bobot' => '5%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 29,
                'grub_fasemonitor' => 'Teknis',
                'fase_monitoring' => 'Generatif Akhir',
                'parameter' => 'Populasi polong',
                'titik_kritis' => '260 polong/tanaman',
                'monitoring_poin' => 'H+40 S/d H+65',
                'bobot' => '20%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 30,
                'grub_fasemonitor' => 'Teknis',
                'fase_monitoring' => 'Generatif Akhir',
                'parameter' => 'Jumlah polong',
                'titik_kritis' => '20 polong/tanaman',
                'monitoring_poin' => 'H+40 S/d H+65',
                'bobot' => '20%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 31,
                'grub_fasemonitor' => 'Teknis',
                'fase_monitoring' => 'Generatif Akhir',
                'parameter' => 'Berat polong',
                'titik_kritis' => '2.8 gram/polong',
                'monitoring_poin' => 'H+40 S/d H+65',
                'bobot' => '20%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 32,
                'grub_fasemonitor' => 'Teknis',
                'fase_monitoring' => 'Generatif Akhir',
                'parameter' => 'Kecukupan air',
                'titik_kritis' => 'Permukaan bedeng kering namun tanaman tidak layu',
                'monitoring_poin' => 'H+40 S/d H+65',
                'bobot' => '5%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 33,
                'grub_fasemonitor' => 'Teknis',
                'fase_monitoring' => 'Generatif Akhir',
                'parameter' => 'Bemisia tabaci',
                'titik_kritis' => 'Serangan dibawah ambang kendali',
                'monitoring_poin' => 'H+40 S/d H+65',
                'bobot' => '10%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 34,
                'grub_fasemonitor' => 'Teknis',
                'fase_monitoring' => 'Generatif Akhir',
                'parameter' => 'Ulat',
                'titik_kritis' => 'Tidak terdapat ulat pada polong/20 tanaman sampel',
                'monitoring_poin' => 'H+40 S/d H+65',
                'bobot' => '5%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
            [
                'id_monitor' => 35,
                'grub_fasemonitor' => 'Teknis',
                'fase_monitoring' => 'Generatif Akhir',
                'parameter' => 'Empoasca',
                'titik_kritis' => 'Serangan dibawah ambang kendali',
                'monitoring_poin' => 'H+40 S/d H+65',
                'bobot' => '20%',
                'keterangan' => '',
                'field1' => '',
                'field2' => '',
            ],
        ];

        foreach ($fasemonitors as $fasemonitor) {
            MstFasemonitor::create($fasemonitor);
        }
    }
}
